alias v="nvim"
alias la="ls -lha"
alias lg="lazygit"
alias sz="source ~/.zshrc"
alias ns="npm start"
alias ngl="npm ls --depth=0 -g"
alias y="yarn"
alias ys="yarn start"
alias yp="yarn pstart"
alias yc="yarn compile"
alias ya="yarn add"
alias yad="yarn add -D"
alias yga="yarn global add"
alias yr="yarn remove"
alias ygl="yarn global list"
alias yo="yarn outdated"
alias ra="ranger"
alias gfp="git fetch -p"
alias chrome="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --remote-debugging-port=9222"
alias c="chezmoi"
