alias v="nvim"
alias lg="lazygit"
alias la="ls -lah --color=auto"
alias sz="source ~/.zshrc"
alias ns="npm start"
alias ngl="npm list -g"
alias y="yarn"
alias ys="yarn start"
alias yp="yarn pstart"
alias yc="yarn compile"
alias ya="yarn add"
alias yad="yarn add -D"
alias yga="yarn global add"
alias yr="yarn remove"
alias ygl="yarn global list"
alias yo="yarn outdated"
alias gs="git status"
function gc { git commit -m "$@"; }
alias gcb="git checkout -b"
alias gp="git push"
alias gl="git pull"
alias gcl="git clone"
alias ga="git add ."
alias gd="git diff"
alias gst="git status"
alias gfp="git fetch -p"
alias glog="git log --oneline --pretty --graph"
alias chrome="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --remote-debugging-port=9222"
alias c="chezmoi"
alias k="kubectl"
alias kgp="kubectl get pods"
alias kcu="kubectl config use-context"
alias kcn="kubectl config set-context --current --namespace"
alias pn="pnpm"
